### PR TITLE
👷 (build): Add binary build & release on GitHub.

### PR DESCRIPTION
**Pull request by jakehamilton**
## Description

This PR adds automated builds of the CLI to releases on GitHub using [`pkg`](https://github.com/vercel/pkg). Binary builds allow users without Node.js and npm to use the CLI without installing other software.

## Tests

- [x] All tests passed.

### CODE REVIEW

**Comment by carloscuesta** [comment]
I've merged a PR to fix your CI 🔴 could you rebase with master ? @jakehamilton 

Thanks 🙏

**Comment by carloscuesta** [comment]
Hey @jakehamilton I've merged a pr to fix your pipeline, could you make a rebase to fix the merge conflicts ?

Thanks!

**Comment by jakehamilton** [comment]
Hey @carloscuesta, thank you for your patience 🙏
I've been distracted with work, but I'll try and get this PR updated this weekend so we can have things merged in!

**Comment by jakehamilton** [comment]
@carloscuesta, the weekend came early 😂

**Comment by carloscuesta** [comment]
Thanks @jakehamilton ❤️

**Comment by carloscuesta** [comment]
Hey @jakehamilton seems that the github action is broken, could you take a look ?

https://github.com/carloscuesta/gitmoji-cli/runs/767871303?check_suite_focus=true

**Comment by carloscuesta** [comment]
No worries, I think i fixed it on 😊 

https://github.com/carloscuesta/gitmoji-cli/commit/54302b96d33c14ec483df50a8454eebd4aeaaa63

**Pull request merged**
