### PR TITLE
use .cache/gitmoji folder for cache to respect xdg specifications

### PR DESCRIPTION
**Pull request by ccoVeille**
## Description

Update the script to use a xdg compliant folder for cache file.

Issue: #893

### CODE REVIEW

**Comment by carloscuesta** [comment]
Hey! Thanks for opening a PR, sorry If I did not explain myself properly, but I don't want to implement this change to the cli,

I'm happy with the current implementation (doesn't depends on another folders such as `.cache`) and I would not like to leave a "useless" `.gitmoji` folder if we change now the path

I'll close this PR, thanks 😊

**Comment by ccoVeille** [comment]
:unamused: but ok.

**Comment by realitymolder** [comment]
> Hey! Thanks for opening a PR, sorry If I did not explain myself properly, but I don't want to implement this change to the cli,
> 
> I'm happy with the current implementation (doesn't depends on another folders such as `.cache`) and I would not like to leave a "useless" `.gitmoji` folder if we change now the path
> 
> I'll close this PR, thanks 😊 

Why not support an env variable to be changeable for the users that DO want to move the files? 
Unfortunately, I had to delete the program until it support the standard...

**Comment by carloscuesta** [comment]
Hey locking this discussion as it was closed feel free to reopen

Remember you can always fork the project if you're not happy with the decisions 😊

Beauty of open source

**Pull request closed without merging**
