### PR TITLE
Print Git command if it failed

### PR DESCRIPTION
**Pull request by capsuleman**
## Description

If commit fails to execute, cli prints command so it can be copy / paste without executing again gitmoji-cli.
Updated the tests too.

Issue: #680

## Tests

- [x] All tests passed.

### CODE REVIEW

**Comment by carloscuesta** [comment]
Hey! Is there any difference between copying the command from the output of the error and using the arrow up key to replicate the same comand without having to manually copy&pasting it? IMHO using arrow key should be much faster, so I don't really see the point of this 🤔

**Comment by capsuleman** [comment]
> Hey!
> 
> Thanks for opening a PR
> 
> Is there any difference between copying the command from the output of the error and using the arrow up key to replicate the same comand without having to manually copy&pasting it? IMHO using arrow key should be much faster, so I don't really see the point of this thinking

When I use gitmoji -c, I do not provide any other parameters and enter gitmoji and message in the cli. If I use arrow up key, I can not find again the parameters I filled previously.
If there is a quick way without copy/paste, I would be happy to hear it! :-)

**Comment by carloscuesta** [comment]
I think a screenshot/demo about this would be really helpful 😊

**Comment by capsuleman** [comment]
https://user-images.githubusercontent.com/34281913/133271612-c1f9d80e-65c7-481a-8def-c9b0affb3006.mp4

**Comment by carloscuesta** [comment]
Thanks for sharing! But this is the current behaviour right? I was asking for a demo of your change to see what is printed, thank you 🙏🏼

**Comment by capsuleman** [comment]
Oh sorry, I was just wondering if I was using the cli well. With the new version the command would be printed if it fail

https://user-images.githubusercontent.com/34281913/133651823-59186433-54e9-49dc-bac4-b121c00b2dfc.mp4

**Comment by carloscuesta** [comment]
Thanks for sharing the demo! 

Currently, we have a way for specifying the default parameters through the cli. With this you can retry the command faster if it fails as prefills all the questions from the cli.

> Screen Shot 2021-09-19 at 10 06 50

I'm not 100% if this is worth to be added into the cli 😅

**Comment by capsuleman** [comment]
Yes sure, but often I think about the gitmoji, title and message after having typed `gitmoji -c`...
Would you prefer having the command with default values printed? Is there a parameter to provide a gitmoji?

**Review by carloscuesta — APPROVED** [review]
Let's merge it 😊

**Pull request merged**
