### PR TITLE
Title Template Support :sparkles:

### PR DESCRIPTION
**Pull request by avaly**
## Description

Adds a new configuration option to customize the commit title template

## Tests

- [x] All tests passed.

### CODE REVIEW

**Comment by carloscuesta** [comment]
Hey @avaly 😄! 

Thanks for sending a Pull Request. Honestly, I don't think we need to template the commit title. Gitmojis should be used at the start of a commit to identify the purpose of a commit at first without reading the whole commit.

Before implementing any feature, feel free to create an issue first 💪

**Comment by avaly** [comment]
Hi @carloscuesta! Sorry to hear you don't feel this is worth merging. I actually prefer to use my emoji at the end of the commit title. I'll use my fork instead.

**Comment by carloscuesta** [comment]
Feel free @avaly 😄

**Comment by angelikao** [comment]
Sad that the idea was rejected because in my current project it is required by the client to put issueId first and then we could put gitmoji before the describing commit message, so for example 'ISS-102 💯 Adding some description'.

**Comment by carloscuesta** [comment]
Then probably gitmoji it’s not the convention you need to use for that particular project! However you can always try to negotiate the commits convention and explain the benefits @angelikao

**Pull request closed without merging**
