### PR TITLE
✏️ Fix some typos in the code

### PR DESCRIPTION
**Pull request by ccoVeille**
## Description

I applied recommendations based on the following tools:
* https://github.com/codespell-project/codespell
* https://github.com/crate-ci/typos

I didn't create an issue for fixing typos

## Tests

- [X] All tests passed.

### CODE REVIEW

**Review by carloscuesta — COMMENTED** [review]
Hey! Thanks for raising this PR, I will happily merge it if we remove the changes for the cache! 🙏🏼

**Comment by ccoVeille** [comment]
> Hey! Thanks for raising this PR, I will happily merge it if we remove the changes for the cache! 🙏🏼

what a noob :facepalm: ! I didn't expect to open an MR with the first commit

**Review by carloscuesta — APPROVED** [review]
Thanks!

**Comment by carloscuesta** [comment]
> what a noob 🤦 ! I didn't expect to open an MR with the first commit

It's fine no worries 😊

**Pull request merged**
